AY2223S1-CS2103T-T11-4/tp

- docs/team/carriezhengjr.md
A sample PPP template is provided.
This should be updated with actual team members' PPP to describe one's contributions to the project.
Let's create a skeletal version of PPP for carriezhengjr.
Fixes #13
> Add a skeletal PPP: add carriezhengjr

- docs/DeveloperGuide.md
Update the Developer Guide with more use cases. 
Textual user cases for creating user, deleting user, add a tag, search a user.
> Add use case to Developer Guide

- docs/team/jonasgwt.md
Fixes https://github.com/AY2223S1-CS2103T-T11-4/tp/issues/17
Add skeleton PPP.
Details to be filled up are temporarily placed with placeholders.
> Add jonasgwt skeletal PPP

- docs/AboutUs.md
Fixes https://github.com/AY2223S1-CS2103T-T11-4/tp/issues/12
> Update AboutUs with jonasgwt details

- src/main/java/seedu/address/logic/commands/ExitCommand.java
The app already has an "exit" command to close application which works well.
Only the acknowledgement message could be made
more specific to our own app.
Let's change Address Book to Mass Linkers in
acknowledgement message of ExitCommand class.
Fixes #51 .
> Close application with command

- docs/UserGuide.md
find command is out-dated; it does not include find using other parameters like Telegram and Github.
It should be updated to reflect the latest changes and plan so that it could be sent for review by the Prof.
Let's update the User Guide to the latest version.
> Update User Guide: include all current and proposed features

- src/main/resources/view/DarkTheme.css
- src/main/resources/view/ResultDisplay.fxml
Very minor changes to make selected card more obvious.
> Fix Bug + Make selected card more obvious

- README.md
- docs/UserGuide.md
- docs/index.md
> Update UG for v1.3

- src/main/java/seedu/address/logic/commands/AddInterestCommand.java
- src/main/java/seedu/address/logic/parser/AddInterestCommandParser.java
- src/main/java/seedu/address/model/person/Person.java
- src/test/java/seedu/address/logic/commands/AddInterestCommandTest.java
* Make code more consistent
* Currently, some places are set and some places are observable list for interests
* Aligns with DG
> Change interests to Set from Observable List

- docs/UserGuide.md
Spotted a mistake in the command table 😨
> Fix backticks typo in User Guide

- src/main/java/seedu/address/logic/commands/ModCommand.java
- src/main/java/seedu/address/logic/commands/ModMarkAllCommand.java
- src/main/java/seedu/address/logic/commands/ModMarkCommand.java
- src/main/java/seedu/address/logic/parser/ModCommandParser.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/ui/HelpWindow.java
Add `mod mark all MODULE [MORE_MODULES]...`
Fixes #91 .
> Mod mark all

- build.gradle
- docs/AboutUs.md
- docs/team/sltsheryl.md
> Update sltsheryl AboutUs 

- docs/team/sltsheryl.md
I noticed a grammatical error sorry 🤦‍♀️
> Fix grammar mistake in AboutUs

- docs/AboutUs.md
- docs/team/carriezhengjr.md
> Update carriezhengjr AboutUs

- docs/DeveloperGuide.md
* Update testing instructions 
* Added testing instructions for `add`, `mod add`, `mod mark`
Not sure if we need to add testing instructions for more commands.
Fixes #156
> Update Manual Testing Instructions

- docs/UserGuide.md
- docs/team/sltsheryl.md
> Check and edit errors in UG

- docs/UserGuide.md
- src/main/java/seedu/masslinkers/model/student/Mod.java
> Fix some bugs in UG

- docs/UserGuide.md
> Fix documentation bugs in UG

- src/main/java/seedu/masslinkers/logic/commands/AddCommand.java
- src/main/java/seedu/masslinkers/logic/commands/EditCommand.java
- src/main/java/seedu/masslinkers/model/MassLinkers.java
- src/main/java/seedu/masslinkers/model/Model.java
- src/main/java/seedu/masslinkers/model/ModelManager.java
- src/main/java/seedu/masslinkers/model/student/Student.java
- src/main/java/seedu/masslinkers/model/student/UniqueStudentList.java
- src/test/java/seedu/masslinkers/logic/commands/AddCommandTest.java
- src/test/java/seedu/masslinkers/model/MassLinkersTest.java
- src/test/java/seedu/masslinkers/model/ModelManagerTest.java
- src/test/java/seedu/masslinkers/model/student/StudentTest.java
- src/test/java/seedu/masslinkers/model/student/UniqueStudentListTest.java
> Add duplicates prevention

- docs/DeveloperGuide.md
- docs/UserGuide.md
> Improve DG and UG + Add FAQs

- docs/UserGuide.md
Fix `<` and `>` display bug in UG by rephrasing the sentence.
> Fix display bug in UG

- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/team/sltsheryl.md
Spotted a duplicate section - View Batchmate.
Add note to sequence diagram. 
Bolded code words in UG warning. 
Edited tense mistake in PPP.
> Remove duplicate View Batchmate feature written in UG

- docs/UserGuide.md
- docs/_sass/minima/custom-styles.scss
I also experimented with changing the color of the headers in UG to be our app color. I hope it won't turn out weird 🤔
> Added Using the User Guide section

- docs/_sass/minima/custom-styles.scss
> Change color of headers

- docs/UserGuide.md
- docs/_sass/minima/custom-styles.scss
Purple and blue was too inconspicuous.
Actually purple is fine, just make it bold?
> Make headers bold

- docs/UserGuide.md
- docs/_sass/minima/_layout.scss
- docs/_sass/minima/custom-styles.scss
Sorry just noticed, the headers became too small.
> Documentation changes

- docs/UserGuide.md
- docs/_sass/minima/_layout.scss
Viewed the UG again and the first few sections looked so lumped together.
Added numbering in UG
> Add line separator in UG

- README.md
- docs/UserGuide.md
Fixes #230 
Fixes #238 
Fixes #233
> Refactor UG to be user centric and include headers overview

- docs/DeveloperGuide.md
- docs/index.md
Don't think this is a bug? Pretty sad can't change this, I just noticed this feature doesn't exist
> Add Future Developments DG alphabetical sort

- src/main/java/seedu/masslinkers/model/student/Phone.java
removed stackoverflow link to avoid confusion in giving credit for reused work (nothing in the link was reused here)
simplified the regex pattern a bit
> minor edits

- docs/UserGuide.md
> Check documentation

- docs/_sass/minima/_layout.scss
- docs/_sass/minima/custom-styles.scss
When I tried converting to pdf, the purple looked so dull, close to black 🥲
So I brightened it a bit
> Make purple more visible

- docs/team/carriezhengjr.md
PPP is 3 pages, which exceeds the hard limit of 2 pages.
Let's shorten the PPP to adhere to the page limit.
> Edit and shorten PPP to page limit

- docs/DeveloperGuide.md
- docs/UserGuide.md
> Fix english
